Add Fedora to known packages
so-fancy/diff-so-fancy pull request #452
Opened 2023-01-18 09:23 UTC by principis

Hi! I have packaged diff-so-fancy for Fedora because I really like this project and use it daily.

This means that diff-so-fancy is available in the official Fedora repositories and can be installed with: `dnf install diff-so-fancy`. If there are any issues with the package on Fedora not related to upstream, users can submit a bug report on bugzilla. There is also a direct link on the [package page](https://packages.fedoraproject.org/pkgs/diff-so-fancy/diff-so-fancy/).

If you have any further questions, feel free to contact me via email!

2023-01-18 12:44 UTC, OJFord requested changes
Otherwise LGTM

2023-01-18 12:44 UTC, OJFord commented on README.md
> +`diff-so-fancy` is also available from the [NPM registry](https://www.npmjs.com/package/diff-so-fancy), [brew](https://formulae.brew.sh/formula/diff-so-fancy), and as a package on [Nix](https://githu
Just minor for better flow:
```suggestion
`diff-so-fancy` is also available from the [NPM registry](https://www.npmjs.com/package/diff-so-fancy), [brew](https://formulae.brew.sh/formula/diff-so-fancy), and as a package on [Nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/version-management/git-and-tools/diff-so-fancy/default.nix), [Fedora](https://packages.fedoraproject.org/pkgs/diff-so-fancy/diff-so-fancy/), in the [Arch community repo](https://archlinux.org/packages/community/any/diff-so-fancy/), and [ppa:aos for Debian/Ubuntu Linux](https://github.com/aos/dsf-debian).
```

2023-01-18 16:16 UTC, scottchiefbaker commented
@principis as a Fedora user that's great! I fully support d-s-f being available in more distro repos. 

Did you package up the fatpacked version?

2023-01-18 16:44 UTC, principis commented
> @principis as a Fedora user that's great! I fully support d-s-f being available in more distro repos.
> 
> Did you package up the fatpacked version?

No, just the script. You can find the spec file here: https://src.fedoraproject.org/rpms/diff-so-fancy/blob/rawhide/f/diff-so-fancy.spec

2023-01-18 17:12 UTC, scottchiefbaker commented
@principis that works too. I usually recommend packagers use the fatpacked/static release version:

https://github.com/so-fancy/diff-so-fancy/releases/tag/v1.4.3

It's a single file, no dependencies, and simpler.

2023-01-19 12:42 UTC, principis commented
@scottchiefbaker I didn't know about the fatpacked version. On Fedora everything must be build from source, but I'm not sure what effect that has on perl. If you want, I can ask the Perl SIG what their preference is.

2023-01-19 14:14 UTC, merged

2023-01-19 14:15 UTC, scottchiefbaker commented
@principis the docs are fine. Thanks for you hard work of getting it in to Fedora.

You're welcome to package it however you want. It might be easier to use the single file version. Up you you.

Thanks again.